### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by Caichy-2000** [FrankWanger/ML_Peptide#1]
Thanks for your wonderful work!!! It gives me much inspiration. Could you please provide your dataset used in your paper for further research? Thank you again!

**Comment by FrankWanger** [comment]
> Thanks for your wonderful work!!! It gives me much inspiration. Could you please provide your dataset used in your paper for further research? Thank you again!

Hi Caichy,

Many thanks for your interest in our work. I have noticed your request. We are currently under the process of compiling and uploading it to FigShare. And I believe it will be ready in a few days. Stay tuned.

Best,
Fanjin

**Comment by FrankWanger** [comment]
> > Thanks for your wonderful work!!! It gives me much inspiration. Could you please provide your dataset used in your paper for further research? Thank you again!
> 
> Hi Caichy,
> 
> Many thanks for your interest in our work. I have noticed your request. We are currently under the process of compiling and uploading it to FigShare. And I believe it will be ready in a few days. Stay tuned.
> 
> Best, Fanjin

Hey Caichy,

We have now made this dataset available on FigShare. Please find it in the readme document of this repo.

Best,
Fanjin

**Comment by Caichy-2000** [comment]
> > > Thanks for your wonderful work!!! It gives me much inspiration. Could you please provide your dataset used in your paper for further research? Thank you again!
> > 
> > 
> > Hi Caichy,
> > Many thanks for your interest in our work. I have noticed your request. We are currently under the process of compiling and uploading it to FigShare. And I believe it will be ready in a few days. Stay tuned.
> > Best, Fanjin
> 
> Hey Caichy,
> 
> We have now made this dataset available on FigShare. Please find it in the readme document of this repo.
> 
> Best, Fanjin

I have already downloaded. Thank you again!!!
